# Generated by Django 3.0 on 2020-08-20 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webregister',
            name='end_on',
        ),
        migrations.AlterField(
            model_name='webregister',
            name='created_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
