# Generated by Django 3.0 on 2020-08-20 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200820_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webregister',
            name='name',
        ),
    ]
