# Generated by Django 3.0 on 2020-08-24 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_customuser_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='webregister',
            name='ends_on',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
