# Generated by Django 3.0 on 2020-08-24 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_webregister_ends_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventregisterationuser',
            name='header_eventimage',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
