# Generated by Django 3.0 on 2020-08-25 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200824_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='webregister',
            options={'ordering': ['-created_on']},
        ),
    ]
